### ISSUE TITLE
Incorrect results returned from shows/id/progress/watched

### ISSUE THREAD

**Issue by mpfc75** [trakt/api-help#298] opened 2021-07-01 20:29 UTC
For some shows `shows/id/progress/watched` is occasionally returning incorrect results.  For example, I have marked all the episodes of the show “Lucifer” (slug = “lucifer”, traktid = 98990) watched yet the API reports that I have only completed 29 of the 83 aired episodes.  

Most of the time it returns the correct number of completed shows.  I have seen this behavour a few times for various shows.

![image](https://user-images.githubusercontent.com/47704863/124185269-c0346a00-da88-11eb-983d-a4d9be5752b8.png)

![image](https://user-images.githubusercontent.com/47704863/124185232-b0b52100-da88-11eb-913a-113d7bf04711.png)

**Comment by kevincador** [comment] 2021-07-02 06:59
@rectifyer I also see that from time to time myself and I have some users reporting it also. It's really random and difficult to debug. It seems like a caching issue server side. I've also seen that sometimes at the "same moment" on my iPhone everything is correct and another device gets an incorrect response for /progress. One way to fix the issue is to mark something watch/unwatched to refresh the cache and get a new correct response.

I'll try to get logs of this, I guess you'll need the headers with the cache id or something.

**Comment by kevincador** [comment] 2021-10-17 18:21
@rectifyer I have more reports of this currently from users. 

The thing is, when it happens, they manually try to refresh their "to watch" list (which is a heavy process even when a lot of the data is cached) but nothing changes. 

The only solution is to watch/checkin something then undo it. At that point the progress is refreshed and correct. 

I've seen that sometimes the data is correct with one call and wrong with another. The difference between the two is a parameter. Everything is pointing at a cache issue.

Would there be a way to fix this? Maybe an api endpoint to recalculate/refresh the progress for a show?

**Comment by rectifyer** [comment] 2021-10-17 19:17
Do you have specific steps to reproduce the issue?

**Comment by kevincador** [comment] 2021-10-17 19:27
No specific steps. Sometimes it even gets messed up for old shows I didn't watch in a while so it's not really a user action that breaks the progress. Maybe when the show is updated the progress is recalculated for each users?

**Comment by rectifyer** [comment] 2021-10-17 20:06
Could be. I’ve looked it this issue several times in the last and never got anywhere since I can’t reproduce the issue. I can try again this week, so please let me know if you find any specific steps. Thanks!

**Comment by kevincador** [comment] 2021-10-18 08:15
And FYI, I have the same issue on another show (last watched 2 days ago). So it's not really the last one I watched it's really random. And it's not missing like the last episode. For the first show it's 5 episodes (all watched in a 2 weeks span) and for the other one it's 4 episodes (2-3 week watch span). I watched other episodes in that same span from other shows that aren't missing anything. What I mean is it's not always the last watched episodes or show. Really random. Sometimes it's only 1 show I didn't watch in like a year or something.

**Comment by kevincador** [comment] 2021-11-29 07:46
Hi @rectifyer, any news on this issue? I've had several reports of this with Rippple.

I, myself, experienced the issue yesterday. My "To Watch" was showing the wrong next episode and progress (so data coming from the API - no app logic) for two different shows.

I pushed an FAQ and added the workaround there so I guess I'll have less reports but I'll try to send you a message when I experience it myself.

Do you need requests/response or anything to help debug this? It's not always easy to get them but doable if it can help.

**Comment by greatvc** [comment] 2022-02-07 12:47
Is there any update on this. I see it on Ripple also and on any other app.

I have a custom windows app that i'm using API calls to get calendar information about episodes that i haven't watched. Over the last month the issue is far worst. I get some crazy results of old shows with 200 episodes unwatched. It happens for many shows not one as it was at the beginning. And it is crazy totally random.

I also have for example the show "Goldbergs" where i'm on season 9 watch only the 4 episodes and the return API call says that i have only one episode left to watch.

**Comment by greatvc** [comment] 2022-03-01 17:46
Is there any update on this ? it is getting pretty frustrating, almost every second time from 80 unwatched episodes i get 280, 400, 100 and so on.

Also on my own APP with my own API i get weird results due to this bug.

Have you managed to culprit the situation ?

Best Regards,
Vassilis

**Comment by 123Venom** [comment] 2022-03-14 06:09
I've seen this happen now twice last couple months as well as 2 users inquiring about it.  Seems as if during some form of maintenance the server responds with incorrect results and seems to self fix in about an hour.  I cross checked the site data when it happened and the site was on point but api response was WAY off.  Very odd behavior indeed.

<img width="1142" alt="show counts wrong" src="https://user-images.githubusercontent.com/46383815/158114663-6f2b1462-3c0d-423c-92d7-c53f938d75e4.PNG">

45mins late it self fixed and we had made no changes to any watched status.

<img width="624" alt="show counts right" src="https://user-images.githubusercontent.com/46383815/158114671-a7a954e9-0c40-43b3-bc52-8d36639943f2.PNG">

**Comment by rectifyer** [comment] 2022-03-16 18:01
No updates yet, it's extremely hard to reproduce or have a series of steps to reproduce it.

**Comment by rectifyer** [comment] 2022-03-18 21:44
I just pushed a potential fix to the API. I still couldn't reproduce the problem, but I adjusted how some data is cached and I'm hoping that fixes the bug. Let me know!

**Comment by 123Venom** [comment] 2022-03-19 00:00
Will keep an eye and report back. Thank you @rectifyer

**Comment by greatvc** [comment] 2022-03-23 07:28
Well, after the pushed fix so far i didn't have a weird return of results. Im pretty sure that i should have because it was happening daily but noting.
Can else verify this ?
Maybe @rectifyer crashed this 🐛

**Comment by tysonkerridge** [comment] 2022-03-23 07:54
Seems like it's hasn't popped up for me since the change also 🤞🏼

**Comment by rectifyer** [comment] 2022-04-02 04:09
Still working ok?

**Comment by greatvc** [comment] 2022-04-02 08:48
> Still working ok?

yeap! no problem at all !!!!!!!
very good work Justin ! 👍

**Closed** 2022-04-13 14:18 UTC
